### ISSUE TITLE
Problem with underscore and italic with certain variable names.

### ISSUE THREAD

**Issue by pierrepaullavoie** [svivian/q2a-markdown-editor#7]
Some questions use names such as Foo_Bar. If the name occurs twice pagedown seems to detect it as an italic directive.

This sentence:

Lorem Foo_Bar is Foo_Bar ipsum.

will look like

Lorem Foo _Bar is Foo_ Bar ipsum.

without the space preceding the first Bar and succeeding the second Foo.

For example. Github flavored markdown does not allow for starting italic mid-word using this syntax.

It is possible to correct this behavior (not allow starting italic mid word and end it mid word) or disable the underscore as an italic operator?

**Comment by costasdroid** [comment]
This is a very common issue. For the workaround, I found two regex of replacing the proper string. One inside `inc.markdown.php` and the other inside `Markdown.Converter.js`. By changing both or one at the time neither of them worked.

I have a major problem with my math notations. Of course I can use `\_` every time, but I have already wrote a whole bunch of exercises without the escape `\`. Can you at least point out what to change in what file in order to bypass `_` midword as @pierrepaullavoie mentioned?
